server:
  port: 8082

spring:
  application:
    name: service2
  cloud:
    discovery:
      client:
        simple:
          instances:
            service1:
              - uri:http://localhost:8081
            service2:
              - uri:http://localhost:8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/